version: "3.9"
services:
  ckan:
    image: "openknowledge/ckan-dev:2.9"
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@postgres/ckan_test
      - CKAN_DATASTORE_WRITE_URL=postgresql://datastore_write:pass@postgres/datastore_test
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_read:pass@postgres/datastore_test
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN__DATAPUSHER__CALLBACK_URL_BASE=http://ckan:5000
      - TZ=UTC
      - CKAN_SYSADMIN_NAME=ckan_admin
      - CKAN_SYSADMIN_PASSWORD=test1234
      - CKAN_SYSADMIN_EMAIL=mail@example.com
    ports:
      - "5000:5000"
  postgres:
    image: "ckan/ckan-postgres-dev:2.9"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  solr: 
    image: "ckan/ckan-solr:2.9"
  redis:
    image: "redis:5.0.14"
