name: Learning github actions

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start containers
        run: docker compose -f "docker/docker-compose.yml" up -d --build

      # - name: Sleeping
      #   run: sleep 10

      - name: Test ckan
        run: curl http://localhost:8000/
