name: Learning github actions

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: isbang/compose-action@v1.4.0
        with:
          compose-file: "./docker/docker-compose.yml"

      # - name: Start containers
      #   run: docker compose -f "docker/docker-compose.yml" up -d --build

      - name: Check containers
        run: docker ps -a

      - name: Check container log
        run: docker logs docker_ckan_1

      - name: Test redis
        run: curl http://localhost:8000/redis

      - name: Test db
        run: curl http://localhost:8000/db

      - name: Test solr
        run: curl http://localhost:8000/solr
