name: Learning github actions

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start containers
        run: docker compose -f "docker/docker-compose.yml" up -d --build

      - uses: r-lib/actions/setup-r@v2

      - run: Rscript -e 'print("hello")'

      - name: Check container docker-ckan-1 logs
        run: docker logs docker-ckan-1
